name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes: { label: Summary }
    validations: { required: true }
  - type: textarea
    id: details
    attributes: { label: Details / acceptance criteria }
