# EDMO Pipeline Configuration - Development

pipeline:
    name: "EDMO Communication Analysis"
    version: "0.1.0"
    log_level: "DEBUG"

audio:
    sample_rate: 16000
    channels: 1
    format: "wav"
    codec: "pcm_s16le"

video:
    frame_rate: 1
    format: "png"

services:
    nlp:
        host: "localhost"
        port: 8001
        url: "http://127.0.0.1:8001"

    asr:
        host: "localhost"
        port: 8002
        url: "http://127.0.0.1:8002"
        model: "base" # tiny, base, small, medium, large

    diarization:
        host: "localhost"
        port: 8003
        url: "http://127.0.0.1:8003"

    emotion:
        host: "localhost"
        port: 8004
        url: "http://127.0.0.1:8004"

    clustering:
        host: "localhost"
        port: 8005
        url: "http://127.0.0.1:8005"

    visualization:
        host: "localhost"
        port: 8006
        url: "http://127.0.0.1:8006"

    nonverb_features:
        host: "localhost"
        port: 8007
        url: "http://127.0.0.1:8007"

    robot_data:
        host: "localhost"
        port: 8008
        url: "http://127.0.0.1:8008"

    movement_tracker:
        host: "localhost"
        port: 8009
        url: "http://127.0.0.1:8009"

features:
    time_window: 30 # seconds
    overlap: 15 # seconds

    speech:
        extract_prosody: true
        extract_embeddings: true
        embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

    emotion:
        model: "j-hartmann/emotion-english-distilroberta-base"

    robot:
        metrics:
            - "distance_to_target"
            - "distance_moved"
            - "action_count"
            - "action_distribution"
            - "action_strength"

clustering:
    algorithm: "fuzzy_cmeans"
    n_clusters: 5
    max_iter: 150
    error: 0.005

    dimensionality_reduction:
        method: "pca" # pca, tsne, umap
        n_components: 3
        explained_variance_threshold: 0.70

privacy:
    anonymize_data: true
    gdpr_compliant: true
    retention_days: 90

paths:
    data: "./data"
    models: "./data/models"
    outputs: "./data/outputs"
